### ISSUE TITLE
class Slack is missing ....

### ISSUE THREAD

**Issue by DeepDiver1975** [jeremykenedy/slack-laravel#15]
Because there is no real class Slack phpstan is reporting issues:
Call to static method send() on an unknown class Slack. 

Same for IDEs like PHPStorm where the class is marked as not existing and as a result autocomplete on methods is not working either:

![Screenshot from 2020-09-30 11-18-31](https://user-images.githubusercontent.com/1005065/94667161-b7064900-030e-11eb-87f6-5758fa52a1e0.png)

**Comment by gugglegum** [comment]
Why it has been closed?

**Comment by DeepDiver1975** [comment]
Can we please have some feedback? THX

**Comment by jeremykenedy** [comment]
Hit the wrong button earlier while looking at it

**Comment by jeremykenedy** [comment]
`Slack` is an alias declared by `composer.json`.

Thre is no `Slack` class. 

The alias links to the package code via Facade.

The package code registers itself via the service provider and the same facade accessor is used when creating a singleton in the service provider.

**Comment by DeepDiver1975** [comment]
Yeah. This is how facades in laravel work.
But still other facades provide a class so that this all work properly.
